export type TransactionType = 'expense' | 'income';

export type RecurringFrequency = 'weekly' | 'monthly' | 'quarterly' | 'yearly';

export type PaymentMethod = 'upi' | 'net_banking' | 'credit_card' | 'debit_card' | 'cash' | 'auto_debit' | 'bank_transfer' | 'other';

export interface Category {
  id: string;
  name: string;
  icon: string;
  color: string;
  type: TransactionType;
  isCustom?: boolean;
}

export interface Transaction {
  id: string;
  title: string;
  amount: number;
  type: TransactionType;
  categoryId: string;
  date: string; // YYYY-MM-DD
  paymentMethod: PaymentMethod;
  accountId?: string;
  isRecurring?: boolean;
  recurringFrequency?: RecurringFrequency;
  notes?: string;
  tags?: string[];
  subscriptionId?: string; // Links if generated by subscription
  receiptUrl?: string; // Base64 or local image URL
  createdAt: string;
}

export interface Subscription {
  id: string;
  name: string;
  amount: number;
  categoryId: string;
  billingCycle: RecurringFrequency;
  startDate: string; // YYYY-MM-DD
  nextBillingDate: string; // YYYY-MM-DD
  paymentMethod: PaymentMethod;
  accountId?: string;
  notes?: string;
  active: boolean;
  autoLogTransaction?: boolean;
  color?: string;
  icon?: string;
  website?: string;
}

export interface Budget {
  id: string;
  categoryId: string; // 'total' or specific categoryId
  monthlyLimit: number;
  alertThreshold: number; // e.g. 80 for 80%
}

export interface SavingsGoal {
  id: string;
  name: string;
  targetAmount: number;
  currentAmount: number;
  deadline?: string; // YYYY-MM-DD
  color: string;
  icon: string;
  notes?: string;
}

export type AccountType = 'checking' | 'savings' | 'credit_card' | 'cash' | 'investment';

export interface Account {
  id: string;
  name: string;
  type: AccountType;
  balance: number;
  institution?: string;
  color: string;
  icon: string;
  isLiability?: boolean; // For credit cards or loans where balance represents money owed
  upiId?: string; // Optional UPI VPA (e.g. user@okhdfcbank)
}

export interface SplitParticipant {
  name: string;
  share: number;
  hasPaid: boolean;
  upiId?: string;
}

export interface BillSplit {
  id: string;
  title: string;
  totalAmount: number;
  date: string;
  paidBy: string;
  participants: SplitParticipant[];
  yourShare: number;
  upiId?: string; // UPI handle to receive funds
  notes?: string;
}

export type TimeframeMode = 'monthly' | 'yearly' | 'financial_year' | 'all' | 'custom';

export interface DateFilter {
  mode: TimeframeMode;
  year: number;
  month: number; // 0-11
  financialYear?: string; // e.g. '2026-27' (April 1, 2026 to March 31, 2027)
  startDate?: string;
  endDate?: string;
}

export interface CurrencyConfig {
  code: string;
  symbol: string;
  name: string;
  rate: number; // relative to USD baseline
}

export interface ToastMessage {
  id: string;
  title: string;
  message?: string;
  type: 'success' | 'error' | 'info' | 'warning';
}

export interface ParsedMagicExpense {
  title: string;
  amount: number;
  categoryId: string;
  date: string;
  paymentMethod: PaymentMethod;
  notes?: string;
  confidence: number;
}

export interface ForecastSummary {
  currentSpent: number;
  projectedDiscretionary: number;
  upcomingScheduledBills: number;
  estimatedMonthEndSpend: number;
  dailyBurnRate: number;
  daysRemaining: number;
  totalDays: number;
  projectedNetSavings: number;
}
